//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalAra {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalAra() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resources.GlobalAra", typeof(GlobalAra).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة ملفات.
        /// </summary>
        public static string AddMore {
            get {
                return ResourceManager.GetString("AddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرفاق.
        /// </summary>
        public static string AssosiateItem {
            get {
                return ResourceManager.GetString("AssosiateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string Closebtn {
            get {
                return ResourceManager.GetString("Closebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنشأ من قبل.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Deletebtn {
            get {
                return ResourceManager.GetString("Deletebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستند.
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المستند.
        /// </summary>
        public static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستندات.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الوثيقة.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الملف.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف البضاعة.
        /// </summary>
        public static string GoodDescription {
            get {
                return ResourceManager.GetString("GoodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزن الإجمالي.
        /// </summary>
        public static string GrossWeight {
            get {
                return ResourceManager.GetString("GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز المستند.
        /// </summary>
        public static string Hsccode {
            get {
                return ResourceManager.GetString("Hsccode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم البند.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البند.
        /// </summary>
        public static string ItemNumber {
            get {
                return ResourceManager.GetString("ItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البند.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المُصنِع.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزن الكلي.
        /// </summary>
        public static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الطرود.
        /// </summary>
        public static string NoOfPackages {
            get {
                return ResourceManager.GetString("NoOfPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ملاحظة: أقصى حجم للملف هو 500 من الأنواع التالية فقط pdf.
        /// </summary>
        public static string notifcation {
            get {
                return ResourceManager.GetString("notifcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إزالة.
        /// </summary>
        public static string Removebtn {
            get {
                return ResourceManager.GetString("Removebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة المستندات المحددة.
        /// </summary>
        public static string SelectedDocumentsList {
            get {
                return ResourceManager.GetString("SelectedDocumentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        public static string UploadBtn {
            get {
                return ResourceManager.GetString("UploadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل المستندات.
        /// </summary>
        public static string UploadDocuments {
            get {
                return ResourceManager.GetString("UploadDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التحميل.
        /// </summary>
        public static string UploadedDate {
            get {
                return ResourceManager.GetString("UploadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض/تنزيل.
        /// </summary>
        public static string ViewDownload {
            get {
                return ResourceManager.GetString("ViewDownload", resourceCulture);
            }
        }
    }
}
